### PR TITLE
Adding in pdf creation / optional command line arguments / checking for sufficient data

### PR DESCRIPTION
**Pull request by cplummer-uwm**
Categories code was broken when I wrote this so it inspired to add more error checking with the counts and not try to generate a pdf or image when there is no data because that leads to different errors. 

Added in error check if less than 1 counts then will not create images / pdf
Added in file checking for cover page - if images were not created it will not try to add them to pdf
Added in optional command line arguments
Delete example files
Made the email icon and blue color more generic
Added in Lisa's fix for sorting messages.

The command line options here are pretty flexible. You can use the short option or long option (e.g. -n or --number). You can use some of the command option and let it ask for the remaining items or you can re-arrange the order on the command line. Or you can ask for help with -h or --help

Some example so you can try:
```
python3 outlook_analyzer.py
python3 outlook_analyzer.py -n <max number of email> -s <starting> -e <end cutoff>
python3 outlook_analyzer.py -h
python3 outlook_analyzer.py --help
python3 outlook_analyzer.py -n 100
python3 outlook_analyzer.py -n 100 -s 6m 
python3 outlook_analyzer.py -n 100 -s 6m -e 6d
python3 outlook_analyzer.py -n 100 -s 6m -e 6d -O True
python3 outlook_analyzer.py -n 100 -s 6m -e 6d -O True -o 'C:/Users/<user>/Downloads/test.pdf'
python3 outlook_analyzer.py --number 100 --start 6m --end 6d
python3 outlook_analyzer.py --start 6m --end 6d --number 100

```

### CODE REVIEW

**Review by lisashub — COMMENTED** [review]
I'm getting the below errors from the delete_temp_files() function when running the version in your latest PR? Thought maybe they were coming from my PDF editor being already open, but they occur even when I've close the editor.  Have these popped up for you before?

`function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-155607_a001.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-155607_b001.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-155607_b002.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-155607_b003.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-155607_b004.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-160047_a001.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-160047_b001.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-160047_b002.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-160047_b003.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-160047_b004.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-160438_a001.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-160438_b001.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-160438_b002.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-160438_b003.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-160438_b004.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-161029_a001.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-161029_b001.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-161029_b002.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-161029_b003.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-161029_b004.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-161812_a001.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-161812_b001.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-161812_b002.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-161812_b003.pdf'
function: delete_temp_files | error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\WINDOWS\\Temp\\outlookanalyzer\\20220424-161812_b004.pdf'`

**Comment by cplummer-uwm** [comment]
I was getting those errors if I tried to delete the pdf files of the current execution. I updated the code to delete the temp files from the previous execution so it would stop happening. I'm not seeing those errors anymore when I run it.

**Comment by cplummer-uwm** [comment]
I'm not sure if it will solve the problem but I added this line:
```
merger.close()
```
into the pdf_merge function

**Comment by lisashub** [comment]
> I'm not sure if it will solve the problem but I added this line:
> 
> ```
> merger.close()
> ```
> 
> into the pdf_merge function

Yep, that did fix trick. Thank you!

**Review by lisashub — APPROVED** [review]

**Pull request merged**
