### PR TITLE
Create requirements.txt

### PR DESCRIPTION
**Pull request by lisashub**
* Generated requirements.txt using pipreqs: https://pypi.org/project/pipreqs/
* Added instructions to README.md for automatically installing all package dependencies from requirements.txt

### CODE REVIEW

**Comment by cplummer-uwm** [comment]
How does it come up with these requirements? Numpy isn't even imported in the code but it is in the requirements file. 
Here are the errors I got when running it
EDIT: The error message says that matplotlib and pandas use numpy so maybe that is the answer. 
```
C:\Users\churn\Documents\GitHub\outlookanalyzer>pip install -r requirements.txt
Requirement already satisfied: dataframe_image==0.1.1 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 1)) (0.1.1)
Requirement already satisfied: fpdf==1.7.2 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 2)) (1.7.2)
Requirement already satisfied: matplotlib==3.5.1 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 3)) (3.5.1)
Collecting numpy==1.20.3
  Downloading numpy-1.20.3.zip (7.8 MB)
     ---------------------------------------- 7.8/7.8 MB 4.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pandas==1.4.1
  Downloading pandas-1.4.1-cp310-cp310-win_amd64.whl (10.6 MB)
     ---------------------------------------- 10.6/10.6 MB 4.0 MB/s eta 0:00:00
Requirement already satisfied: Pillow==9.1.0 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 6)) (9.1.0)
Requirement already satisfied: python_dateutil==2.8.2 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 7)) (2.8.2)
Collecting pywin32==302
  Downloading pywin32-302-cp310-cp310-win_amd64.whl (9.2 MB)
     ---------------------------------------- 9.2/9.2 MB 4.5 MB/s eta 0:00:00
Requirement already satisfied: tabulate==0.8.9 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 9)) (0.8.9)
Collecting tqdm==4.63.0
  Downloading tqdm-4.63.0-py2.py3-none-any.whl (76 kB)
     ---------------------------------------- 76.6/76.6 KB ? eta 0:00:00
Requirement already satisfied: wordcloud==1.8.1 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 11)) (1.8.1)
Requirement already satisfied: requests in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from dataframe_image==0.1.1->-r requirements.txt (line 1)) (2.27.1)
Requirement already satisfied: beautifulsoup4 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from dataframe_image==0.1.1->-r requirements.txt (line 1)) (4.10.0)
Requirement already satisfied: aiohttp in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from dataframe_image==0.1.1->-r requirements.txt (line 1)) (3.8.1)
Requirement already satisfied: nbconvert>=5 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from dataframe_image==0.1.1->-r requirements.txt (line 1)) (6.4.5)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from matplotlib==3.5.1->-r requirements.txt (line 3)) (1.4.2)
Requirement already satisfied: cycler>=0.10 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from matplotlib==3.5.1->-r requirements.txt (line 3)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from matplotlib==3.5.1->-r requirements.txt (line 3)) (4.31.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from matplotlib==3.5.1->-r requirements.txt (line 3)) (3.0.7)
Requirement already satisfied: packaging>=20.0 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from matplotlib==3.5.1->-r requirements.txt (line 3)) (21.3)
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of numpy to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of matplotlib to determine which version is compatible with other requirements. This could take a while.
Collecting matplotlib==3.5.1
  Using cached matplotlib-3.5.1-cp310-cp310-win_amd64.whl (7.2 MB)
INFO: pip is looking at multiple versions of fpdf to determine which version is compatible with other requirements. This could take a while.
Collecting fpdf==1.7.2
  Using cached fpdf-1.7.2.tar.gz (39 kB)
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of dataframe-image to determine which version is compatible with other requirements. This could take a while.
Collecting dataframe_image==0.1.1
  Using cached dataframe_image-0.1.1-py3-none-any.whl (32 kB)
ERROR: Cannot install -r requirements.txt (line 3), -r requirements.txt (line 5) and numpy==1.20.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.20.3
    matplotlib 3.5.1 depends on numpy>=1.17
    pandas 1.4.1 depends on numpy>=1.21.0; python_version >= "3.10"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by cplummer-uwm** [comment]
I was able to get a clean install by using 
numpy==1.21.0
in the requirements file

**Review by cplummer-uwm — APPROVED** [review]

**Comment by lisashub** [comment]
> numpy==1.21.0

Awesome, I appreciate your taking the initiative to look into the errors and resolve it.  Good teamwork! Numpy 1.21.0 was giving me the below error, so I've changed it to 1.20.0 which gives me a clean install. Could you check that it does the same for you, as well? If not, could you share the full error again?

> (base) C:\Users\eelis\Documents\GitHub\outlookanalyzer>pip install -r requirements.txt
Requirement already satisfied: dataframe_image==0.1.1 in c:\users\eelis\anaconda3\lib\site-packages (from -r requirements.txt (line 1)) (0.1.1)
Requirement already satisfied: fpdf==1.7.2 in c:\users\eelis\anaconda3\lib\site-packages (from -r requirements.txt (line 2)) (1.7.2)
Requirement already satisfied: matplotlib==3.5.1 in c:\users\eelis\anaconda3\lib\site-packages (from -r requirements.txt (line 3)) (3.5.1)
Collecting numpy==1.21.0
  Downloading numpy-1.21.0-cp39-cp39-win_amd64.whl (14.0 MB)
     |████████████████████████████████| 14.0 MB 3.3 MB/s
Requirement already satisfied: pandas==1.4.1 in c:\users\eelis\anaconda3\lib\site-packages (from -r requirements.txt (line 5)) (1.4.1)
Collecting Pillow==9.1.0
  Downloading Pillow-9.1.0-cp39-cp39-win_amd64.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 6.8 MB/s
Requirement already satisfied: python_dateutil==2.8.2 in c:\users\eelis\anaconda3\lib\site-packages (from -r requirements.txt (line 7)) (2.8.2)
Requirement already satisfied: pywin32==302 in c:\users\eelis\anaconda3\lib\site-packages (from -r requirements.txt (line 8)) (302)
Requirement already satisfied: tabulate==0.8.9 in c:\users\eelis\anaconda3\lib\site-packages (from -r requirements.txt (line 9)) (0.8.9)
Requirement already satisfied: tqdm==4.63.0 in c:\users\eelis\anaconda3\lib\site-packages (from -r requirements.txt (line 10)) (4.63.0)
Requirement already satisfied: wordcloud==1.8.1 in c:\users\eelis\anaconda3\lib\site-packages (from -r requirements.txt (line 11)) (1.8.1)
Requirement already satisfied: aiohttp in c:\users\eelis\anaconda3\lib\site-packages (from dataframe_image==0.1.1->-r requirements.txt (line 1)) (3.8.1)
Requirement already satisfied: requests in c:\users\eelis\anaconda3\lib\site-packages (from dataframe_image==0.1.1->-r requirements.txt (line 1)) (2.27.1)
Requirement already satisfied: beautifulsoup4 in c:\users\eelis\anaconda3\lib\site-packages (from dataframe_image==0.1.1->-r requirements.txt (line 1)) (4.10.0)
Requirement already satisfied: nbconvert>=5 in c:\users\eelis\anaconda3\lib\site-packages (from dataframe_image==0.1.1->-r requirements.txt (line 1)) (6.4.4)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\eelis\anaconda3\lib\site-packages (from matplotlib==3.5.1->-r requirements.txt (line 3)) (1.3.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\eelis\anaconda3\lib\site-packages (from matplotlib==3.5.1->-r requirements.txt (line 3)) (4.25.0)
Requirement already satisfied: cycler>=0.10 in c:\users\eelis\anaconda3\lib\site-packages (from matplotlib==3.5.1->-r requirements.txt (line 3)) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\eelis\anaconda3\lib\site-packages (from matplotlib==3.5.1->-r requirements.txt (line 3)) (3.0.4)
Requirement already satisfied: packaging>=20.0 in c:\users\eelis\anaconda3\lib\site-packages (from matplotlib==3.5.1->-r requirements.txt (line 3)) (21.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\eelis\anaconda3\lib\site-packages (from pandas==1.4.1->-r requirements.txt (line 5)) (2021.3)
Requirement already satisfied: six>=1.5 in c:\users\eelis\anaconda3\lib\site-packages (from python_dateutil==2.8.2->-r requirements.txt (line 7)) (1.16.0)
Requirement already satisfied: colorama in c:\users\eelis\anaconda3\lib\site-packages (from tqdm==4.63.0->-r requirements.txt (line 10)) (0.4.4)
Requirement already satisfied: jupyter-core in c:\users\eelis\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (4.9.2)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\eelis\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (0.3)
Requirement already satisfied: bleach in c:\users\eelis\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (4.1.0)
Requirement already satisfied: traitlets>=5.0 in c:\users\eelis\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (5.1.1)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\eelis\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (1.5.0)
Requirement already satisfied: testpath in c:\users\eelis\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (0.5.0)
Requirement already satisfied: defusedxml in c:\users\eelis\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (0.7.1)
Requirement already satisfied: pygments>=2.4.1 in c:\users\eelis\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (2.11.2)
Requirement already satisfied: nbformat>=4.4 in c:\users\eelis\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (5.1.3)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\eelis\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (0.8.4)
Requirement already satisfied: jinja2>=2.4 in c:\users\eelis\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (2.11.3)
Requirement already satisfied: jupyterlab-pygments in c:\users\eelis\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (0.1.2)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\eelis\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (0.5.11)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\eelis\anaconda3\lib\site-packages (from jinja2>=2.4->nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: nest-asyncio in c:\users\eelis\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (1.5.1)
Requirement already satisfied: jupyter-client>=6.1.5 in c:\users\eelis\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (6.1.12)
Requirement already satisfied: pyzmq>=13 in c:\users\eelis\anaconda3\lib\site-packages (from jupyter-client>=6.1.5->nbclient<0.6.0,>=0.5.0->nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (22.3.0)
Requirement already satisfied: tornado>=4.1 in c:\users\eelis\anaconda3\lib\site-packages (from jupyter-client>=6.1.5->nbclient<0.6.0,>=0.5.0->nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (6.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\eelis\anaconda3\lib\site-packages (from nbformat>=4.4->nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (3.2.0)
Requirement already satisfied: ipython-genutils in c:\users\eelis\anaconda3\lib\site-packages (from nbformat>=4.4->nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (0.2.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\eelis\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.4->nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (21.4.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\eelis\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.4->nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (0.18.0)
Requirement already satisfied: setuptools in c:\users\eelis\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.4->nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (61.2.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\eelis\anaconda3\lib\site-packages (from aiohttp->dataframe_image==0.1.1->-r requirements.txt (line 1)) (2.0.4)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\eelis\anaconda3\lib\site-packages (from aiohttp->dataframe_image==0.1.1->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\eelis\anaconda3\lib\site-packages (from aiohttp->dataframe_image==0.1.1->-r requirements.txt (line 1)) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\eelis\anaconda3\lib\site-packages (from aiohttp->dataframe_image==0.1.1->-r requirements.txt (line 1)) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\eelis\anaconda3\lib\site-packages (from aiohttp->dataframe_image==0.1.1->-r requirements.txt (line 1)) (1.7.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\eelis\anaconda3\lib\site-packages (from aiohttp->dataframe_image==0.1.1->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: idna>=2.0 in c:\users\eelis\anaconda3\lib\site-packages (from yarl<2.0,>=1.0->aiohttp->dataframe_image==0.1.1->-r requirements.txt (line 1)) (3.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\eelis\anaconda3\lib\site-packages (from beautifulsoup4->dataframe_image==0.1.1->-r requirements.txt (line 1)) (2.3.1)
Requirement already satisfied: webencodings in c:\users\eelis\anaconda3\lib\site-packages (from bleach->nbconvert>=5->dataframe_image==0.1.1->-r requirements.txt (line 1)) (0.5.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\eelis\anaconda3\lib\site-packages (from requests->dataframe_image==0.1.1->-r requirements.txt (line 1)) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\eelis\anaconda3\lib\site-packages (from requests->dataframe_image==0.1.1->-r requirements.txt (line 1)) (1.26.8)
Installing collected packages: Pillow, numpy
  Attempting uninstall: Pillow
    Found existing installation: Pillow 9.0.1
    Uninstalling Pillow-9.0.1:
      Successfully uninstalled Pillow-9.0.1
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.3
    Uninstalling numpy-1.20.3:
      Successfully uninstalled numpy-1.20.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.54.1 requires numpy<1.21,>=1.17, but you have numpy 1.21.0 which is incompatible.
Successfully installed Pillow-9.1.0 numpy-1.21.0

**Comment by cplummer-uwm** [comment]
1.20.0 errors for me. See error below
Every system will be different so not sure if will work with specific values for all cases
```
C:\Users\churn\Documents\GitHub\outlookanalyzer>pip install -r requirements.txt
Requirement already satisfied: dataframe_image==0.1.1 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 1)) (0.1.1)
Requirement already satisfied: fpdf==1.7.2 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 2)) (1.7.2)
Requirement already satisfied: matplotlib==3.5.1 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 3)) (3.5.1)
Collecting numpy==1.20.0
  Downloading numpy-1.20.0.zip (8.0 MB)
     ---------------------------------------- 8.0/8.0 MB 3.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pandas==1.4.1 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 5)) (1.4.1)
Requirement already satisfied: Pillow==9.1.0 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 6)) (9.1.0)
Requirement already satisfied: python_dateutil==2.8.2 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 7)) (2.8.2)
Requirement already satisfied: pywin32==302 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 8)) (302)
Requirement already satisfied: tabulate==0.8.9 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 9)) (0.8.9)
Requirement already satisfied: tqdm==4.63.0 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 10)) (4.63.0)
Requirement already satisfied: wordcloud==1.8.1 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 11)) (1.8.1)
Requirement already satisfied: beautifulsoup4 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from dataframe_image==0.1.1->-r requirements.txt (line 1)) (4.10.0)
Requirement already satisfied: requests in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from dataframe_image==0.1.1->-r requirements.txt (line 1)) (2.27.1)
Requirement already satisfied: aiohttp in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from dataframe_image==0.1.1->-r requirements.txt (line 1)) (3.8.1)
Requirement already satisfied: nbconvert>=5 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from dataframe_image==0.1.1->-r requirements.txt (line 1)) (6.4.5)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from matplotlib==3.5.1->-r requirements.txt (line 3)) (3.0.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from matplotlib==3.5.1->-r requirements.txt (line 3)) (1.4.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from matplotlib==3.5.1->-r requirements.txt (line 3)) (4.31.2)
Requirement already satisfied: packaging>=20.0 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from matplotlib==3.5.1->-r requirements.txt (line 3)) (21.3)
Requirement already satisfied: cycler>=0.10 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from matplotlib==3.5.1->-r requirements.txt (line 3)) (0.11.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\churn\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from pandas==1.4.1->-r requirements.txt (line 5)) (2022.1)
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of numpy to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of matplotlib to determine which version is compatible with other requirements. This could take a while.
Collecting matplotlib==3.5.1
  Using cached matplotlib-3.5.1-cp310-cp310-win_amd64.whl (7.2 MB)
INFO: pip is looking at multiple versions of fpdf to determine which version is compatible with other requirements. This could take a while.
Collecting fpdf==1.7.2
  Using cached fpdf-1.7.2.tar.gz (39 kB)
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of dataframe-image to determine which version is compatible with other requirements. This could take a while.
Collecting dataframe_image==0.1.1
  Using cached dataframe_image-0.1.1-py3-none-any.whl (32 kB)
ERROR: Cannot install -r requirements.txt (line 3), numpy==1.20.0 and pandas==1.4.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.20.0
    matplotlib 3.5.1 depends on numpy>=1.17
    pandas 1.4.1 depends on numpy>=1.21.0; python_version >= "3.10"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
````

**Pull request merged**
